# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 729)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/paypal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(14, 102, 22);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Header.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setLineWidth(0)
        self.Header.setObjectName("Header")
        self.gridLayout = QtWidgets.QGridLayout(self.Header)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_error = QtWidgets.QFrame(self.Header)
        self.frame_error.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 61, 61);\n"
"border-radius: 8px;\n"
"position: absolute;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setLineWidth(2)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_closeError = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_closeError.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_closeError.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close/Images/X.png);\n"
"    background-position:center;\n"
"    background-color: rgb(255, 26, 26);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_closeError.setText("")
        self.pushButton_closeError.setObjectName("pushButton_closeError")
        self.horizontalLayout_3.addWidget(self.pushButton_closeError)
        self.gridLayout.addWidget(self.frame_error, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.Header)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.frame_logo = QtWidgets.QFrame(self.Header)
        self.frame_logo.setMinimumSize(QtCore.QSize(140, 0))
        self.frame_logo.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_logo.setLineWidth(0)
        self.frame_logo.setObjectName("frame_logo")
        self.logo = QtWidgets.QLabel(self.frame_logo)
        self.logo.setGeometry(QtCore.QRect(6, 0, 50, 50))
        self.logo.setMaximumSize(QtCore.QSize(60, 60))
        self.logo.setObjectName("logo")
        self.logoTitle = QtWidgets.QLabel(self.frame_logo)
        self.logoTitle.setGeometry(QtCore.QRect(55, 10, 101, 38))
        self.logoTitle.setMaximumSize(QtCore.QSize(120, 100))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.logoTitle.setFont(font)
        self.logoTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.logoTitle.setObjectName("logoTitle")
        self.logoTitle.raise_()
        self.logo.raise_()
        self.gridLayout.addWidget(self.frame_logo, 0, 0, 1, 1)
        self.frame_logo.raise_()
        self.frame_error.raise_()
        self.frame.raise_()
        self.verticalLayout.addWidget(self.Header)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setLineWidth(0)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginArea = QtWidgets.QFrame(self.content)
        self.loginArea.setMaximumSize(QtCore.QSize(300, 450))
        self.loginArea.setStyleSheet("")
        self.loginArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loginArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginArea.setLineWidth(0)
        self.loginArea.setObjectName("loginArea")
        self.inputText_Email = QtWidgets.QLineEdit(self.loginArea)
        self.inputText_Email.setGeometry(QtCore.QRect(40, 220, 220, 50))
        self.inputText_Email.setAutoFillBackground(False)
        self.inputText_Email.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(14, 78, 20);\n"
"    border-radius: 5px ; \n"
"    padding: 15px;\n"
"    background-color: rgb(254, 254, 254);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border:2px solid  rgb(254, 254, 254); \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    color: rgb(000, 000, 000);\n"
"    border:2px solid  rgb(14, 78, 20); \n"
"}")
        self.inputText_Email.setText("")
        self.inputText_Email.setMaxLength(50)
        self.inputText_Email.setAlignment(QtCore.Qt.AlignCenter)
        self.inputText_Email.setObjectName("inputText_Email")
        self.frame_slogan = QtWidgets.QFrame(self.loginArea)
        self.frame_slogan.setGeometry(QtCore.QRect(25, 20, 250, 80))
        self.frame_slogan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_slogan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slogan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slogan.setObjectName("frame_slogan")
        self.slogan = QtWidgets.QLabel(self.frame_slogan)
        self.slogan.setGeometry(QtCore.QRect(10, 0, 160, 66))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.slogan.setFont(font)
        self.slogan.setObjectName("slogan")
        self.slogan_2 = QtWidgets.QLabel(self.frame_slogan)
        self.slogan_2.setGeometry(QtCore.QRect(150, 32, 77, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.slogan_2.setFont(font)
        self.slogan_2.setStyleSheet("")
        self.slogan_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slogan_2.setObjectName("slogan_2")
        self.avatar = QtWidgets.QFrame(self.loginArea)
        self.avatar.setGeometry(QtCore.QRect(105, 110, 90, 90))
        self.avatar.setStyleSheet("QFrame{\n"
"    \n"
"    background-image: url(:/Avatar/Images/profile circled.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    border-radius: 30px;\n"
"}\n"
"")
        self.avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar.setObjectName("avatar")
        self.inputText_Password = QtWidgets.QLineEdit(self.loginArea)
        self.inputText_Password.setGeometry(QtCore.QRect(40, 280, 220, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.inputText_Password.setFont(font)
        self.inputText_Password.setAutoFillBackground(False)
        self.inputText_Password.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(14, 78, 20);\n"
"    border-radius: 5px ; \n"
"    padding: 15px;\n"
"    background-color: rgb(254, 254, 254);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border:2px solid  rgb(254, 254, 254); \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    color: rgb(000, 000, 000);\n"
"    border:2px solid  rgb(14, 78, 20); \n"
"}")
        self.inputText_Password.setText("")
        self.inputText_Password.setMaxLength(100)
        self.inputText_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputText_Password.setAlignment(QtCore.Qt.AlignCenter)
        self.inputText_Password.setObjectName("inputText_Password")
        self.checkbox_saveUser = QtWidgets.QCheckBox(self.loginArea)
        self.checkbox_saveUser.setGeometry(QtCore.QRect(45, 340, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(9)
        self.checkbox_saveUser.setFont(font)
        self.checkbox_saveUser.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox:indicator{\n"
"    border:3px solid  rgb(7, 51, 10);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(13, 98, 19) ;\n"
"}\n"
"\n"
"QCheckBox:indicator:checked{\n"
"    border:3px solid  rgb(7, 51, 10);\n"
"    background-color: rgb(7, 51, 10) ;\n"
"}\n"
"")
        self.checkbox_saveUser.setObjectName("checkbox_saveUser")
        self.pushButton_newDf = QtWidgets.QPushButton(self.loginArea)
        self.pushButton_newDf.setGeometry(QtCore.QRect(0, 380, 140, 40))
        self.pushButton_newDf.setStyleSheet("QPushButton{\n"
"    background-color: rgb(254, 254, 254);\n"
"    font: 75 10pt \"Inter\";\n"
"    color: rgb(11, 82, 18);\n"
"    border: 2px solid rgb(8, 50, 12);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(64, 155, 71, 250);\n"
"    font: 75 10pt \"Inter\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(10, 65, 15);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(24, 152, 35);\n"
"    font: 75 10pt \"Inter\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(24, 152, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.pushButton_newDf.setDefault(False)
        self.pushButton_newDf.setFlat(False)
        self.pushButton_newDf.setObjectName("pushButton_newDf")
        self.viewDFButton = QtWidgets.QPushButton(self.loginArea)
        self.viewDFButton.setGeometry(QtCore.QRect(160, 380, 140, 40))
        self.viewDFButton.setMinimumSize(QtCore.QSize(105, 0))
        self.viewDFButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(14, 78, 20);\n"
"    font: 75 10pt \"Inter\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(8, 50, 12);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(17, 99, 24);\n"
"    font: 75 10pt \"Inter\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(8, 50, 12);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(24, 152, 35);\n"
"    font: 75 10pt \"Inter\";\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(8, 50, 12);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"")
        self.viewDFButton.setIconSize(QtCore.QSize(16, 16))
        self.viewDFButton.setCheckable(False)
        self.viewDFButton.setChecked(False)
        self.viewDFButton.setObjectName("viewDFButton")
        self.horizontalLayout.addWidget(self.loginArea)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "Senha incorreta"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/Images/paypal.svg\" height=\"50\" width=\"50\"/></p></body></html>"))
        self.logoTitle.setText(_translate("MainWindow", "PSWRD\n"
"MANAGER"))
        self.inputText_Email.setPlaceholderText(_translate("MainWindow", "Informe seu e-mail"))
        self.slogan.setText(_translate("MainWindow", "<html><head/><body><p style=\"color:#FFFFFF\">Manage Your <br/>Passwords</p></body></html>"))
        self.slogan_2.setText(_translate("MainWindow", "<html><head/><body><p style=\"color:#FFFFFF\">Faster</p></body></html>"))
        self.inputText_Password.setPlaceholderText(_translate("MainWindow", "Informe sua chave de criptografia"))
        self.checkbox_saveUser.setText(_translate("MainWindow", "Manter descriptografado"))
        self.pushButton_newDf.setText(_translate("MainWindow", "ADICIONAR NOVO \n"
"BANCO"))
        self.viewDFButton.setText(_translate("MainWindow", "VISUALIZAR BANCO"))
        self.viewDFButton.setShortcut(_translate("MainWindow", "Return"))
import QTImages_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
