# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
 

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 733)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/paypal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setMinimumSize(QtCore.QSize(0, 70))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 70))
        self.Header.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setLineWidth(0)
        self.Header.setObjectName("Header")
        self.gridLayout = QtWidgets.QGridLayout(self.Header)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_logo = QtWidgets.QFrame(self.Header)
        self.frame_logo.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_logo.setMaximumSize(QtCore.QSize(313, 70))
        self.frame_logo.setLineWidth(0)
        self.frame_logo.setObjectName("frame_logo")
        self.logo = QtWidgets.QLabel(self.frame_logo)
        self.logo.setGeometry(QtCore.QRect(6, 0, 50, 50))
        self.logo.setMinimumSize(QtCore.QSize(50, 50))
        self.logo.setMaximumSize(QtCore.QSize(60, 60))
        self.logo.setStyleSheet("")
        self.logo.setObjectName("logo")
        self.logoTitle = QtWidgets.QLabel(self.frame_logo)
        self.logoTitle.setGeometry(QtCore.QRect(60, 5, 101, 38))
        self.logoTitle.setMinimumSize(QtCore.QSize(101, 38))
        self.logoTitle.setMaximumSize(QtCore.QSize(120, 100))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.logoTitle.setFont(font)
        self.logoTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.logoTitle.setObjectName("logoTitle")
        self.logoTitle.raise_()
        self.logo.raise_()
        self.gridLayout.addWidget(self.frame_logo, 0, 0, 1, 1)
        self.frame_error = QtWidgets.QFrame(self.Header)
        self.frame_error.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 61, 61);\n"
"border-radius: 8px;\n"
"position: absolute;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setLineWidth(2)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_closeError = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_closeError.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_closeError.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close/Images/X.png);\n"
"    background-position:center;\n"
"    background-color: rgb(255, 26, 26);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.pushButton_closeError.setText("")
        self.pushButton_closeError.setObjectName("pushButton_closeError")
        self.horizontalLayout_3.addWidget(self.pushButton_closeError)
        self.gridLayout.addWidget(self.frame_error, 0, 1, 1, 1)
        self.frame_empty = QtWidgets.QFrame(self.Header)
        self.frame_empty.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_empty.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_empty.setLineWidth(0)
        self.frame_empty.setObjectName("frame_empty")
        self.gridLayout.addWidget(self.frame_empty, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Header)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setLineWidth(0)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.content)
        self.sidebar.setMinimumSize(QtCore.QSize(200, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar.setStyleSheet("background-color: rgb(14, 102, 22);")
        self.sidebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.avatar = QtWidgets.QLabel(self.sidebar)
        self.avatar.setGeometry(QtCore.QRect(8, 20, 51, 51))
        self.avatar.setMaximumSize(QtCore.QSize(60, 60))
        self.avatar.setStyleSheet("")
        self.avatar.setText("")
        self.avatar.setPixmap(QtGui.QPixmap("Images/profile circled.svg"))
        self.avatar.setScaledContents(True)
        self.avatar.setObjectName("avatar")
        self.criptografia_warnText_2 = QtWidgets.QLabel(self.sidebar)
        self.criptografia_warnText_2.setGeometry(QtCore.QRect(65, 15, 131, 41))
        self.criptografia_warnText_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.criptografia_warnText_2.setFont(font)
        self.criptografia_warnText_2.setScaledContents(True)
        self.criptografia_warnText_2.setObjectName("criptografia_warnText_2")
        self.pushButton_passwords = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_passwords.setGeometry(QtCore.QRect(0, 90, 201, 50))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_passwords.setFont(font)
        self.pushButton_passwords.setStyleSheet("QPushButton{\n"
"    background-color: rgb(14, 102, 22);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(39, 119, 46);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(24, 152, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Key/Images/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_passwords.setIcon(icon1)
        self.pushButton_passwords.setAutoDefault(False)
        self.pushButton_passwords.setDefault(False)
        self.pushButton_passwords.setFlat(True)
        self.pushButton_passwords.setObjectName("pushButton_passwords")
        self.criptografia_warnText_3 = QtWidgets.QLabel(self.sidebar)
        self.criptografia_warnText_3.setGeometry(QtCore.QRect(65, 60, 125, 20))
        self.criptografia_warnText_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.criptografia_warnText_3.setFont(font)
        self.criptografia_warnText_3.setScaledContents(True)
        self.criptografia_warnText_3.setObjectName("criptografia_warnText_3")
        self.pushButton_notes = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_notes.setGeometry(QtCore.QRect(0, 140, 201, 50))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_notes.setFont(font)
        self.pushButton_notes.setStyleSheet("QPushButton{\n"
"    background-color: rgb(14, 102, 22);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(39, 119, 46);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(24, 152, 35);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Bookmark/Images/bookmark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_notes.setIcon(icon2)
        self.pushButton_notes.setDefault(False)
        self.pushButton_notes.setFlat(True)
        self.pushButton_notes.setObjectName("pushButton_notes")
        self.pushButton_wifiPass = QtWidgets.QPushButton(self.sidebar)
        self.pushButton_wifiPass.setGeometry(QtCore.QRect(0, 189, 201, 50))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_wifiPass.setFont(font)
        self.pushButton_wifiPass.setStyleSheet("QPushButton{\n"
"    background-color: rgb(14, 102, 22);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(39, 119, 46);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(24, 152, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(188, 212, 190);\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/WifiPass/Images/wifiPass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_wifiPass.setIcon(icon3)
        self.pushButton_wifiPass.setDefault(False)
        self.pushButton_wifiPass.setFlat(True)
        self.pushButton_wifiPass.setObjectName("pushButton_wifiPass")
        self.pushButton_notes.raise_()
        self.avatar.raise_()
        self.criptografia_warnText_2.raise_()
        self.pushButton_passwords.raise_()
        self.criptografia_warnText_3.raise_()
        self.pushButton_wifiPass.raise_()
        self.horizontalLayout.addWidget(self.sidebar)
        self.Galery = QtWidgets.QFrame(self.content)
        self.Galery.setStyleSheet("background-color: rgb(191, 203, 192);")
        self.Galery.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Galery.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Galery.setObjectName("Galery")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Galery)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.Galery)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_6)
        self.frame_4.setMinimumSize(QtCore.QSize(257, 38))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setGeometry(QtCore.QRect(0, 10, 215, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(215, 18))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-radius: 5px ; \n"
"    padding: 15px;\n"
"    background-color: rgb(254, 254, 254); \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(220, 5, 30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-image: url(:/Search/Images/search.svg);\n"
"    background-repeat: no-repeat;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(218, 231, 219);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(218, 231, 230);\n"
"    border-radius: 5px;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.scrollArea = QtWidgets.QScrollArea(self.Galery)
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"   \n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 774, 623))
        self.scrollAreaWidgetContents.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR - HOMEWORK */\n"
"QScrollBar:horizontal {\n"
"   \n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    \n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"\n"
"}\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_PSWRDItem = QtWidgets.QFrame(self.frame_12)
        self.frame_PSWRDItem.setMinimumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem.setMaximumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PSWRDItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PSWRDItem.setLineWidth(0)
        self.frame_PSWRDItem.setObjectName("frame_PSWRDItem")
        self.pushButton_addNewPSWRD = QtWidgets.QPushButton(self.frame_PSWRDItem)
        self.pushButton_addNewPSWRD.setEnabled(True)
        self.pushButton_addNewPSWRD.setGeometry(QtCore.QRect(22, 16, 194, 240))
        self.pushButton_addNewPSWRD.setMinimumSize(QtCore.QSize(194, 240))
        self.pushButton_addNewPSWRD.setMaximumSize(QtCore.QSize(194, 240))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_addNewPSWRD.setFont(font)
        self.pushButton_addNewPSWRD.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_addNewPSWRD.setStyleSheet("QPushButton{\n"
"    background-color: rgb(254, 254, 254);\n"
"    font: 75 13pt \"Inter\";\n"
"\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.pushButton_addNewPSWRD.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/AddPSWRD/Images/add_circled.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addNewPSWRD.setIcon(icon4)
        self.pushButton_addNewPSWRD.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_addNewPSWRD.setCheckable(False)
        self.pushButton_addNewPSWRD.setAutoRepeat(False)
        self.pushButton_addNewPSWRD.setAutoExclusive(False)
        self.pushButton_addNewPSWRD.setObjectName("pushButton_addNewPSWRD")
        self.label_2 = QtWidgets.QLabel(self.frame_PSWRDItem)
        self.label_2.setGeometry(QtCore.QRect(39, 180, 160, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.frame_PSWRDItem, 0, 0, 1, 1)
        self.frame_PSWRDItem2 = QtWidgets.QFrame(self.frame_12)
        self.frame_PSWRDItem2.setMinimumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem2.setMaximumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PSWRDItem2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PSWRDItem2.setObjectName("frame_PSWRDItem2")
        self.gridLayout_2.addWidget(self.frame_PSWRDItem2, 0, 2, 1, 1)
        self.frame_PSWRDItem3 = QtWidgets.QFrame(self.frame_12)
        self.frame_PSWRDItem3.setMinimumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem3.setMaximumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PSWRDItem3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PSWRDItem3.setObjectName("frame_PSWRDItem3")
        self.gridLayout_2.addWidget(self.frame_PSWRDItem3, 1, 0, 1, 1)
        self.frame_PSWRDItem5 = QtWidgets.QFrame(self.frame_12)
        self.frame_PSWRDItem5.setMinimumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem5.setMaximumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PSWRDItem5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PSWRDItem5.setObjectName("frame_PSWRDItem5")
        self.gridLayout_2.addWidget(self.frame_PSWRDItem5, 1, 2, 1, 1)
        self.frame_PSWRDItem4 = QtWidgets.QFrame(self.frame_12)
        self.frame_PSWRDItem4.setMinimumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem4.setMaximumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PSWRDItem4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PSWRDItem4.setObjectName("frame_PSWRDItem4")
        self.gridLayout_2.addWidget(self.frame_PSWRDItem4, 1, 1, 1, 1)
        self.frame_PSWRDItem1 = QtWidgets.QFrame(self.frame_12)
        self.frame_PSWRDItem1.setMinimumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem1.setMaximumSize(QtCore.QSize(238, 272))
        self.frame_PSWRDItem1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PSWRDItem1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_PSWRDItem1.setObjectName("frame_PSWRDItem1")
        #
        self.PSWRD1 = QtWidgets.QFrame(self.frame_PSWRDItem1)
        self.PSWRD1.setGeometry(QtCore.QRect(22, 16, 194, 240))
        self.PSWRD1.setMinimumSize(QtCore.QSize(194, 240))
        self.PSWRD1.setMaximumSize(QtCore.QSize(194, 240))
        self.PSWRD1.setStyleSheet("    background-color: rgb(254, 254, 254);\n"
"    font: 75 13pt \"Inter\";\n"
"\n"
"    border-radius: 20px;")
        self.PSWRD1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PSWRD1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PSWRD1.setObjectName("PSWRD1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PSWRD1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.PSWRDIcon = QtWidgets.QPushButton(self.PSWRD1)
        self.PSWRDIcon.setEnabled(True)
        self.PSWRDIcon.setMinimumSize(QtCore.QSize(194, 105))
        self.PSWRDIcon.setMaximumSize(QtCore.QSize(194, 105))

        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)

        self.PSWRDIcon.setFont(font)
        self.PSWRDIcon.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PSWRDIcon.setStyleSheet("QPushButton{\n"
"    background-color: rgb(254, 254, 254);\n"
"    font: 75 13pt \"Inter\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.PSWRDIcon.setText("")
        self.PSWRDIcon.setIcon(icon4)
        self.PSWRDIcon.setIconSize(QtCore.QSize(80, 80))
        self.PSWRDIcon.setCheckable(False)
        self.PSWRDIcon.setAutoRepeat(False)
        self.PSWRDIcon.setAutoExclusive(False)
        self.PSWRDIcon.setObjectName("PSWRDIcon")

        self.verticalLayout_3.addWidget(self.PSWRDIcon)

        self.PSWRDName = QtWidgets.QLabel(self.PSWRD1)

        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)

        self.PSWRDName.setFont(font)
        self.PSWRDName.setAutoFillBackground(False)
        self.PSWRDName.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.PSWRDName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PSWRDName.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PSWRDName.setObjectName("PSWRDName")

        self.verticalLayout_3.addWidget(self.PSWRDName)

        self.PSWRDUser = QtWidgets.QPushButton(self.PSWRD1)
        self.PSWRDUser.setEnabled(True)
        self.PSWRDUser.setMinimumSize(QtCore.QSize(194, 60))
        self.PSWRDUser.setMaximumSize(QtCore.QSize(194, 60))

        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)

        self.PSWRDUser.setFont(font)
        self.PSWRDUser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PSWRDUser.setAutoFillBackground(False)
        self.PSWRDUser.setStyleSheet("QPushButton{\n"
"    background-color: rgb(254, 254, 254);\n"
"    font: 75 8pt \"Inter\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/User/Images/User.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.PSWRDUser.setIcon(icon5)
        self.PSWRDUser.setIconSize(QtCore.QSize(30, 30))
        self.PSWRDUser.setCheckable(False)
        self.PSWRDUser.setAutoRepeat(False)
        self.PSWRDUser.setAutoExclusive(False)
        self.PSWRDUser.setObjectName("PSWRDUser")
        
        self.verticalLayout_3.addWidget(self.PSWRDUser)
        
        self.PSWRDPass = QtWidgets.QPushButton(self.PSWRD1)
        self.PSWRDPass.setEnabled(True)
        self.PSWRDPass.setMinimumSize(QtCore.QSize(194, 60))
        self.PSWRDPass.setMaximumSize(QtCore.QSize(194, 60))
        
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        
        self.PSWRDPass.setFont(font)
        self.PSWRDPass.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PSWRDPass.setStyleSheet("QPushButton{\n"
"    background-color: rgb(254, 254, 254);\n"
"    font: 75 8pt \"Inter\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Locker/Images/Locker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        
        self.PSWRDPass.setIcon(icon6)
        self.PSWRDPass.setIconSize(QtCore.QSize(30, 30))
        self.PSWRDPass.setCheckable(False)
        self.PSWRDPass.setAutoRepeat(False)
        self.PSWRDPass.setAutoExclusive(False)
        self.PSWRDPass.setObjectName("PSWRDPass")
        
        self.verticalLayout_3.addWidget(self.PSWRDPass)
        self.gridLayout_2.addWidget(self.frame_PSWRDItem1, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.Galery)
        self.Galery.raise_()
        self.sidebar.raise_()
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/Logo/Images/paypal.svg\" height=\"50\" width=\"50\"/></p></body></html>"))
        self.logoTitle.setText(_translate("MainWindow", "PSWRD\n"
"MANAGER"))
        self.label_error.setText(_translate("MainWindow", "Senha incorreta"))
        self.criptografia_warnText_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">Nome do<br> bancoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</span></p></body></html>"))
        self.pushButton_passwords.setText(_translate("MainWindow", "     Senhas     "))
        self.criptografia_warnText_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; color:#ffffff;\">jose@gmail.com</span></p></body></html>"))
        self.pushButton_notes.setText(_translate("MainWindow", "       Notas      "))
        self.pushButton_wifiPass.setText(_translate("MainWindow", " Senhas wi-fi "))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Encontre sua senha salva"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Adicionar senha</p></body></html>"))
        self.PSWRDName.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">App nº1</p></body></html>"))
        self.PSWRDUser.setText(_translate("MainWindow", "jose@gmail.com"))
        self.PSWRDPass.setText(_translate("MainWindow", "x&r4z32S7HKQ"))
import QTImages_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
